version: '3.9'
services:
  redis:
    image: redis
    hostname: redis
    ports:
      - '6379:6379'
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - type: volume
        source: mongodb_data_volume
        target: /data/db
    hostname: mongo
  schuaro:
    image: 'schuaro:latest'
    build: .
    ports:
      - '80:80'
      - '443:443'
      - '4433:4433/udp'
    volumes:
      - '.:/code'
    container_name: schuaro
    environment:
      schuaro_dev: 'True'
      redis_host: redis
      mongo_host: mongodb

  
volumes:
  mongodb_data_volume:
    external: true
