certfile = "./keys/certificate.pem"
keyfile = "./keys/key.pem"
quic_bind = "0.0.0.0:4433"
bind = "0.0.0.0:443"
insecure_bind = "0.0.0.0:80"
reload = true
loglevel = "debug"
accesslog = "/dev/stdout"
errorlog = "/dev/stdout"