certfile = "./keys/certificate.pem"
keyfile = "./keys/key.pem"
quic_bind = "0.0.0.0:4433"
bind = "0.0.0.0:443"
insecure_bind = "0.0.0.0:80"
reload = true
log_level = "debug"
access_logfile = "./logs/access.log"
error_logfile = "./logs/error.log"